// Code generated by "stringer -type=nodeKind"; DO NOT EDIT.

package ast

import "strconv"

const _nodeKind_name = "unknownfuncDeclfuncAttrfuncConfigstructDeclenumDeclalternativefieldbaseTypedataTypeenumBoolTypepointerTypesliceTypeellipsisTypecbTypemaxNodeKind"

var _nodeKind_index = [...]uint8{0, 7, 15, 23, 33, 43, 51, 62, 67, 75, 83, 95, 106, 115, 127, 133, 144}

func (i nodeKind) String() string {
	if i < 0 || i >= nodeKind(len(_nodeKind_index)-1) {
		return "nodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodeKind_name[_nodeKind_index[i]:_nodeKind_index[i+1]]
}
